  Parameters:
    LatestAmiId:
      Description: Gets the latest AMI from Systems Manager Parameter store
      Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
      Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
    InstanceType:
      Description: WebServer EC2 instance type
      Type: String
      Default: t3.micro
      AllowedValues:
        - t3.nano
        - t3.micro
        - t3.small
        - t2.nano
        - t2.micro
        - t2.small
      ConstraintDescription: must be a valid EC2 instance type.
  Mappings:
    SubnetConfig:
      VPC:
        CIDR: "10.0.0.0/16"
      Public0:
        CIDR: "10.0.1.0/24"
      Public1:
        CIDR: "10.0.2.0/24"
      Private0:
        CIDR: "10.0.10.0/24"
      Private1:
        CIDR: "10.0.20.0/24"
    KeyName:
      EC2:
        Name: "example"  #created before CloudFormation stack 

  Resources:
    VPC:
      Type: "AWS::EC2::VPC"
      Properties:
        EnableDnsSupport: "true"
        EnableDnsHostnames: "true"
        CidrBlock:
          Fn::FindInMap:
            - "SubnetConfig"
            - "VPC"
            - "CIDR"
        Tags:
          - Key: "Application"
            Value:
              Ref: "AWS::StackName"
          - Key: "Network"
            Value: "Public"
          - Key: "Name"
            Value:  !Join ['', [!Ref "AWS::StackName", "-VPC" ]]

    PublicSubnet0:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId:
          Ref: "VPC"
        AvailabilityZone: 
          Fn::Select: 
            - 0
            - Fn::GetAZs: ""
        CidrBlock:
          Fn::FindInMap:
            - "SubnetConfig"
            - "Public0"
            - "CIDR"
        MapPublicIpOnLaunch: "true"
        Tags:
          - Key: "Application"
            Value:
              Ref: "AWS::StackName"
          - Key: "Network"
            Value: "Public"
          - Key: "Name"
            Value:  !Join ['', [!Ref "AWS::StackName", "-public0-subnet" ]]

    PublicSubnet1:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId:
          Ref: "VPC"
        AvailabilityZone:
          Fn::Select: 
            - 1
            - Fn::GetAZs: ""
        CidrBlock:
          Fn::FindInMap:
            - "SubnetConfig"
            - "Public1"
            - "CIDR"
        MapPublicIpOnLaunch: "true"
        Tags:
          - Key: "Application"
            Value:
              Ref: "AWS::StackName"
          - Key: "Network"
            Value: "Public"
          - Key: "Name"
            Value:  !Join ['', [!Ref "AWS::StackName", "-public1-subnet" ]]
    PrivateSubnet0:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId:
          Ref: "VPC"
        AvailabilityZone:
          Fn::Select: 
            - 0
            - Fn::GetAZs: ""
        CidrBlock:
          Fn::FindInMap:
            - "SubnetConfig"
            - "Private0"
            - "CIDR"
        Tags:
          - Key: "Application"
            Value:
              Ref: "AWS::StackName"
          - Key: "Network"
            Value: "Private"
          - Key: "Name"
            Value:  !Join ['', [!Ref "AWS::StackName", "-private0-subnet" ]]
    PrivateSubnet1:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId:
          Ref: "VPC"
        AvailabilityZone:
          Fn::Select: 
            - 1
            - Fn::GetAZs: ""
        CidrBlock:
          Fn::FindInMap:
            - "SubnetConfig"
            - "Private1"
            - "CIDR"
        Tags:
          - Key: "Application"
            Value:
              Ref: "AWS::StackName"
          - Key: "Network"
            Value: "Private"
          - Key: "Name"
            Value:  !Join ['', [!Ref "AWS::StackName", "-private1-subnet" ]]
    InternetGateway:
      Type: "AWS::EC2::InternetGateway"
      Properties:
        Tags:
          - Key: "Application"
            Value:
              Ref: "AWS::StackName"
          - Key: "Network"
            Value: "Public"
          - Key: "Name"
            Value:  !Join ['', [!Ref "AWS::StackName", "-IGW" ]]
    GatewayToInternet:
      Type: "AWS::EC2::VPCGatewayAttachment"
      Properties:
        VpcId:
          Ref: "VPC"
        InternetGatewayId:
          Ref: "InternetGateway"
    PublicRouteTable:
      Type: "AWS::EC2::RouteTable"
      Properties:
        VpcId:
          Ref: "VPC"
        Tags:
          - Key: "Application"
            Value:
              Ref: "AWS::StackName"
          - Key: "Network"
            Value: "Public"
          - Key: "Name"
            Value: !Join ['', [!Ref "AWS::StackName","-public-route-table" ]]
    PublicRoute:
      Type: "AWS::EC2::Route"
      DependsOn: "GatewayToInternet"
      Properties:
        RouteTableId:
          Ref: "PublicRouteTable"
        DestinationCidrBlock: "0.0.0.0/0"
        GatewayId:
          Ref: "InternetGateway"
    PublicSubnetRouteTableAssociation0:
      Type: "AWS::EC2::SubnetRouteTableAssociation"
      Properties:
        SubnetId:
          Ref: "PublicSubnet0"
        RouteTableId:
          Ref: "PublicRouteTable"
    PublicSubnetRouteTableAssociation1:
      Type: "AWS::EC2::SubnetRouteTableAssociation"
      Properties:
        SubnetId:
          Ref: "PublicSubnet1"
        RouteTableId:
          Ref: "PublicRouteTable"
    PublicNetworkAcl:
      Type: "AWS::EC2::NetworkAcl"
      Properties:
        VpcId:
          Ref: "VPC"
        Tags:
          - Key: "Application"
            Value:
              Ref: "AWS::StackName"
          - Key: "Network"
            Value: "Public"
          - Key: "Name"
            Value: !Join ['', [!Ref "AWS::StackName","-public-nacl" ]]
    InboundHTTPPublicNetworkAclEntry:
      Type: "AWS::EC2::NetworkAclEntry"
      Properties:
        NetworkAclId:
          Ref: "PublicNetworkAcl"
        RuleNumber: "100"
        Protocol: "-1"
        RuleAction: "allow"
        Egress: "false"
        CidrBlock: "0.0.0.0/0"
        PortRange:
          From: "0"
          To: "65535"
    OutboundPublicNetworkAclEntry:
      Type: "AWS::EC2::NetworkAclEntry"
      Properties:
        NetworkAclId:
          Ref: "PublicNetworkAcl"
        RuleNumber: "100"
        Protocol: "-1"
        RuleAction: "allow"
        Egress: "true"
        CidrBlock: "0.0.0.0/0"
        PortRange:
          From: "0"
          To: "65535"
    PublicSubnetNetworkAclAssociation0:
      Type: "AWS::EC2::SubnetNetworkAclAssociation"
      Properties:
        SubnetId:
          Ref: "PublicSubnet0"
        NetworkAclId:
          Ref: "PublicNetworkAcl"
    PublicSubnetNetworkAclAssociation1:
      Type: "AWS::EC2::SubnetNetworkAclAssociation"
      Properties:
        SubnetId:
          Ref: "PublicSubnet1"
        NetworkAclId:
          Ref: "PublicNetworkAcl"
    ElasticIP0:
      Type: "AWS::EC2::EIP"
      Properties:
        Domain: "vpc"
    ElasticIP1:
      Type: "AWS::EC2::EIP"
      Properties:
        Domain: "vpc"
    NATGateway0:
      Type: "AWS::EC2::NatGateway"
      Properties:
        AllocationId:
          Fn::GetAtt:
            - "ElasticIP0"
            - "AllocationId"
        SubnetId:
          Ref: "PublicSubnet0"
    NATGateway1:
      Type: "AWS::EC2::NatGateway"
      Properties:
        AllocationId:
          Fn::GetAtt:
            - "ElasticIP1"
            - "AllocationId"
        SubnetId:
          Ref: "PublicSubnet1"
    PrivateRouteTable0:
      Type: "AWS::EC2::RouteTable"
      Properties:
        VpcId:
          Ref: "VPC"
        Tags:
          - Key: "Name"
            Value: !Join ['', [!Ref "AWS::StackName","-private-route-table-0" ]]
    PrivateRouteTable1:
      Type: "AWS::EC2::RouteTable"
      Properties:
        VpcId:
          Ref: "VPC"
        Tags:
          - Key: "Name"
            Value: !Join ['', [!Ref "AWS::StackName","-private-route-table-1" ]]
    PrivateRouteToInternet0:
      Type: "AWS::EC2::Route"
      Properties:
        RouteTableId:
          Ref: "PrivateRouteTable0"
        DestinationCidrBlock: "0.0.0.0/0"
        NatGatewayId:
          Ref: "NATGateway0"
    PrivateRouteToInternet1:
      Type: "AWS::EC2::Route"
      Properties:
        RouteTableId:
          Ref: "PrivateRouteTable1"
        DestinationCidrBlock: "0.0.0.0/0"
        NatGatewayId:
          Ref: "NATGateway1"
    PrivateSubnetRouteTableAssociation0:
      Type: "AWS::EC2::SubnetRouteTableAssociation"
      Properties:
        SubnetId:
          Ref: "PrivateSubnet0"
        RouteTableId:
          Ref: "PrivateRouteTable0"
    PrivateSubnetRouteTableAssociation1:
      Type: "AWS::EC2::SubnetRouteTableAssociation"
      Properties:
        SubnetId:
          Ref: "PrivateSubnet1"
        RouteTableId:
          Ref: "PrivateRouteTable1"

###########
# App Security Group
###########
    PublicSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        VpcId: 
          Ref: "VPC"
        GroupName: !Join ['', [!Ref "AWS::StackName","-public-security-group" ]]
        GroupDescription: >-
          Enable HTTP access via port 22,80 and 443 to the allowed CIDR
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '80'
            ToPort: '80'
            CidrIp: '0.0.0.0/0'
          - IpProtocol: tcp
            FromPort: '443'
            ToPort: '443'
            CidrIp: '0.0.0.0/0'
          - IpProtocol: tcp
            FromPort: '22'
            ToPort: '22'
            CidrIp: '0.0.0.0/0'
        Tags:
          - Key: Name
            Value: !Join ['', [!Ref "AWS::StackName","-public-security-group" ]]
    MyEC2Instance:
          Type: AWS::EC2::Instance
          Properties:
            ImageId: !Ref LatestAmiId
            InstanceType: !Ref InstanceType
            KeyName: 
              Fn::FindInMap:
                - "KeyName"
                - "EC2"
                - "Name"
            Tags:
              - Key: Name
                Value: !Join ['', [!Ref "AWS::StackName","-simple-server" ]]
            NetworkInterfaces:
              - AssociatePublicIpAddress: "true"
                DeviceIndex: "0"
                GroupSet:
                  - Ref: PublicSecurityGroup
                SubnetId:
                  Ref: PublicSubnet0
            UserData:
              Fn::Base64:
                !Sub |
                  #!/bin/bash -xe
                  yum -y update
                  sudo yum install -y httpd
                  sudo systemctl start httpd
                  sudo echo '<h1>Hello from ${AWS::Region}</h1>' > /var/www/html/index.html
                  sudo echo 'ssh-rsa <YOUR_KEY>' >> /root/.ssh/authorized_keys


########################################################################

  Outputs:
    EC2:
      Value: !GetAtt MyEC2Instance.PublicIp



